# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12.0
        environment:
          NODE_OPTIONS: --max-old-space_size=8024
        resource_class: large
    
    working_directory: ~/repo
 
    steps:
 
      - checkout
 
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
 
      # let's install npm
      - run: npm install --silent
 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # copy dist files to digitalocean
  deploy-staging:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bb:44:12:57:7e:fb:dc:f4:48:80:d8:a1:ee:9d:8a:aa"
      - run:
          name: Deploying to staging
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /home/staging/api && git pull https://$GITHUB_USER:$GITHUB_PASS@github.com/$GITHUB_USER/AltoAPI"
      - run:
          name: Installing Node Modules && restarting PM2
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /home/staging/api && npm install && pm2 restart 2"
  deploy-production:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bb:44:12:57:7e:fb:dc:f4:48:80:d8:a1:ee:9d:8a:aa"
      - run:
          name: Deploying to production
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /home/production/api && git pull https://$GITHUB_USER:$GITHUB_PASS@github.com/$GITHUB_USER/AltoAPI"
      - run:
          name: Installing Node Modules && restarting PM2
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /home/production/api && npm install && pm2 restart all"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production